<div id="main-content" class="architect-content">
    <h1>Architectual Arts</h1>
    <section id="architectContent">
        <div class="sideNav">
            <p>Nations</p>
            <ul class="sideNavTier1">
                <li>Americas
                    <ul class="sideNavTier2"><li>North America</li>
                    <li>Central America</li>
                    <li>South America</li></ul>
                </li>
                <li>Europe
                    <ul class="sideNavTier2"><li>Spain</li>
                    <li>Italy</li></ul>
                </li>
                <li>Africa
                    <ul class="sideNavTier2"><li>Mali</li>
                    <li>Ethiopia</li></ul>
                </li>
            </ul>
        </div>
        <div class="photoTable">
            <!--First table will show a base of all available images.  When the user clicks on a topic in the Side Menu the corresponding table will load.-->
            <table class="all-photos architectBase">
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos northAmerica">
                <tr>
                    <th colspan=3>North America</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos centralAmerica">
                <tr>
                    <th colspan=3>Central America</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos southAmerica">
                <tr>
                    <th colspan=3>South America</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos spain">
                <tr>
                    <th colspan=3>Spain</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos italy">
                <tr>
                    <th colspan=3>Italy</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos mali">
                <tr>
                    <th colspan=3>Mali</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
            <table class="all-photos ethiopia">
                <tr>
                    <th colspan=3>Ethiopia</th>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                    <td><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td><img src="" alt="" width="" height=""></td>
                    <td colspan=2><img src="" alt="" width="" height=""></td>
                </tr>
                <tr>
                    <td colspan=3><img src="" alt="" width="" height=""></td>
                </tr>
            </table>
        </div>
    </section>
</div>