<div id="main-content" class="home-content">
    <h1>ArtVentures<br><span class="subheading">The Adventures of Art Around the World</span></h1>
    <section id="homeContent">
        <div class="photoTable">
        <table class="all-photos">
            <tr>
                <td><img src="" alt="" width="" height=""></td>
                <td><img src="" alt="" width="" height=""></td>
                <td><img src="" alt="" width="" height=""></td>
            </tr>
            <tr>
                <td colspan=2><img src="" alt="" width="" height=""></td>
                <td><img src="" alt="" width="" height=""></td>
            </tr>
            <tr>
                <td><img src="" alt="" width="" height=""></td>
                <td colspan=2><img src="" alt="" width="" height=""></td>
            </tr>
            <tr>
                <td colspan=3><img src="" alt="" width="" height=""></td>
            </tr>
        </table>
        </div>
        <div class="main-text-insert">
            <p>ArtVentures travesl the globe in search of mankind's greatest expression...<b>ART</b>! From Timbuktu to Amsterdam, Myanmar to California ArtVentures shares World Arts from Cultures, Architecture and Cuisine with the world.</p>
            <p>Welcome to ArtVentures where <span style="text-decoration:underline; font-weight:bold;">Art is the greatest Adventure.</span></p>
        </div>
    </section>
</div>