<!DOCTYPE html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
<title><?php echo $data?></title><!--DATA variable is obtained from index.php function call in the third position-->
<link rel="stylesheet" href="../css/main.css" type="text/css" media="screen"/>
</head>

<body>
<div id="wrapper">
        <nav  id="mainNav">
            <a href="../index.php">Home</a>
            <a href="../Cultural">Cultural Arts</a>
            <a href="../Cuisine">Arts in Cuisine</a>
            <a href="../Architecture">Architectual Arts</a>
            <a href="../About">About Us</a>
        </nav> 